### ISSUE TITLE
Please do not pollute the two lettered namespace

### ISSUE THREAD

**Issue by NightMachinery** [vishaltelangre/ff#18] opened 2020-05-19 00:11 UTC
Using a short name like `ff` makes me very hesitant to install this tool. Such convenient names should be reserved for user aliases, not for any program to claim. I suggest you change the binary's name to `ffind`, and add a simple `alias ff=ffind` to the installation guide.

**Comment by vishaltelangre** [comment] 2020-05-19 06:51
I disagree. I believe that no operating system restricts to have short and convenient names for the user-installed executables.

The short name `ff` was choosen because I use this tool very frequently every day and the command is very easy to remember and type. So many popular utilities have been named similarly such as [`rg`](https://github.com/BurntSushi/ripgrep), [`ag`](https://github.com/ggreer/the_silver_searcher), [`lsd`](https://github.com/Peltoche/lsd), [`sd`](https://github.com/chmln/sd), etc.

Also, one can always use aliases to tweak the outcome of their `$PATH`.

Since this is not a bug neither it adds any value to this utility, I am going to close this issue. If you have a strong opinion to have more strict guidelines for naming the binaries, please have this discussion at https://github.com/rust-lang/rfcs with the appropriate audience.

**Closed as completed by vishaltelangre** 2020-05-19 06:51 UTC
